version: "3.9"

services:
  discord-bot:
    build: .
    container_name: discord-bot
    env_file: .env
    restart: always
    volumes:
      - .:/bot
    working_dir: /bot
    command: python3 bot.py